### ISSUE TITLE
Please Grade our final project!

### ISSUE THREAD

**Issue by LorenzoZhu** [LorenzoZhu/ASTR-119-Final-Project-3-GroupA#9]
@adwasser  @brantr

**Comment by eyunerman** [comment]
Hello, just a few notes!

We split up the project as following:
 - Astropy_Tutorial done by Elizabeth Yunerman
 - f105 Source Detection and f105 AB magnitudes done by Nina Robbins and Kehan Zhou
 - Extra credit done by Pengpei Zhu

Please let us know if you can't open the python notebooks.

Thank you!
